name: Test Auto Approve, Build, and Update

on:
  workflow_dispatch:
    inputs:
      pr_list:
        description: 'List of PR numbers to approve and build (comma-separated)'
        required: true
      github_token:
        description: 'GitHub token with necessary permissions'
        required: true
jobs:
  approve_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Token Permissions
        run: |
          echo "Debugging token permissions..."
          curl -H "Authorization: token ${{ github.event.inputs.github_token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user

      - name: Merge PRs
        uses: actions/github-script@v3
        env:
          GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
        with:
          script: |
            const prList = "${{ github.event.inputs.pr_list }}".split(',');
            for (const prNumber of prList) {
              try {
                console.log(`Merging PR #${prNumber.trim()}`);
                await github.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: parseInt(prNumber.trim())
                });
              } catch (error) {
                console.error(`Error merging PR #${prNumber.trim()}:`, error);
              }
            }

  build_pr:
    needs: approve_pr
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr_number: ${{ fromJSON(format('["{0}"]', github.event.inputs.pr_list)) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simulate Build PR
        run: |
          echo "Simulating build for PR #${{ matrix.pr_number }}"
          echo "Building Docker image with tag: my-repo:${{ matrix.pr_number }}"
          echo "Pushing Docker image: my-repo:${{ matrix.pr_number }}"

  update_repo:
    needs: build_pr
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr_number: ${{ fromJSON(format('["{0}"]', github.event.inputs.pr_list)) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simulate Update Image Tag
        run: |
          echo "Simulating update of image tag for PR #${{ matrix.pr_number }}"
          echo "Updating image tag to: my-repo:${{ matrix.pr_number }}"
